# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: ConfigMap
metadata:
  {{- with .Values.cookie_cutter }}
  name: {{ .service_name }}.config
  namespace: {{ $.Release.Namespace }}
data:
  application-prod.yaml: |2+
    

    spring:
      kafka:
        group-id: {{ .groupID }}
        client-id: {{ .groupID }}
        bootstrap-servers: {{ $.Values.global.external_kafka.kafka_bootstrap_servers_fqdn}}
        security:
          protocol: SSL
        ssl:
          trust-store-type: PEM
          trust-store-location: file:///ca/ca.crt
          key-store-type: PKCS12 
          key-store-location: file:///client-certificates/user.p12
          key-store-password: ${KAFKA_CLIENT_CERTIFICATE_PASSWORD}

  {{- end}}
