---
name: Run tests on pull request
on:
  pull_request:
    branches: ["develop", "main"]

jobs:
  test-pr-code:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: |
          ./gradlew test \
          --refresh-dependencies \
          -PartifactoryUser=${{ secrets.ARTIFACTORY_USER }} \
          -PartifactoryPassword=${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "build/test-results/test/TEST-*.xml"

  verify-jira-ticket-in-title:
    runs-on: ubuntu-latest

    steps:
      - name: Enforce jira-issue key in pull request title
        uses: ryanvade/enforce-pr-title-style-action@v1
